services:
  - type: web
    name: insurance-premium-service
    runtime: docker
    rootDir: Backend/Premium-ServiceAPI
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: commit